name: Branch CI (Python)
run-name: Branch CI for ${{ github.ref_name }} by ${{ github.actor }}

on:  
  push:
    branches-ignore: [ "main" ]
    paths-ignore: ['README.md']

jobs:
  branch-ci:
    uses: openclimatefix/.github/.github/workflows/branch_ci.yml@main
    secrets: inherit
    with:
      enable_linting: true
      enable_typechecking: true
      tests_folder: "src/satellite_consumer"
      tests_runner: "unittest"

